### ISSUE TITLE
Ban appeal declined.

### ISSUE THREAD

**Issue by ReflectedEight5** [Vetrnn/TheCollectiveGaming-Github#3]
i respect it, but i dont like you lying, 
(Things like making fun of somebody's past parents), never in my life have i ever made fun of Noa's parents, the only thing i have done is ask what happened and i never got an answear, and i respect that, and i dont know what else to say, if me getting more mature and ive changed a lot isn't a good enough thing then i dont know what,
the most i can say is sorry, and mature is that i have more understanding, im also getting older and understanding more which means i also want to hear from Noa in that case if i did and how i did joke about his parents, and when but dont have to be the exact date i did make the joke, but roughly what time... , 
One more thing if i new what had happen it would be easier if i knew what happened so i dont make a joke about it, if i did i would like to say im sorry, if i dont get unbanned or what ever i respect that so much, another thing is that i would love to talk with both of you together, maybe Noa can be the like judge, this might sound like a joke, but im for real, he lets us talk and not talk, he can mute us, and unmute, so we can have a word with each other, i also want to say that i would love to join the discord server for the notifications on the server, for real only reason, because time zones are hard to compare and find time with, so if i get the notifications i would be able to join the stream more often.

Little i showed my background: your turn?

i will bet my life, i did not make a joke about his parents, im serious about it, i also have it hard normally in life, this is more of a little back story stuff, i am suicidal, im not blaming on it, but i am, and that makes me light headed when i think about death, i have lost so many relatives in the last year and before that, im not going to count but its closer relatives and i cant count them on my hand, ive been dealing with cancer since i was 5, i have had Leukemia twice, when i was 5 and when i was 11, you of course didnt now me then, just want to give you context, last year my dog Nova died, that really pushed me to the limit, this was the 30th of November last year, i was 14, that was when i almost did it, just remember that i meet you about one week after this or 2, and i havent told you att all, i tried to take my own life by hanging myself, that was the hardest choice in my life, then my other dog Cosmo came in when i was about to do it, i said that i cant take suicide knowing that there is the cutest thing i have ever seen right in front of me, so i could not, it was impossible, Cosmo is the reason im living, and he doesn't live with me anymore, our cousin has him, i still get to meet him very often, 2 to 3 times a week, but not daily, and that of course effects me, i always feel down these days, and i often just lay in bed waiting for my cousin to maybe call and come with Cosmo, and im now at the point where i cant stand, yes, ive hurt myself so much, that im now in a wheelchair, just for the moments, but i tried jumping from my school 2 weeks ago and broke my legs, i will be recovered in about 2 months, but 2 months without walking at all is harder than you think, onto another thing that in school there are racists, which is because im a jue, im not a jue that believes in like you get it, im not a big believing jue, but my mom is, my mom takes it seriously, which is bad because our family is doing bad rn, my dad and mom are good with each other, they will never break up, and im serious, but my mom is feeling down because my dad is, see my dad has hit the wall, he has worked non stop for (4 years), the only breaks he has taken was his birthday mine and my brothers birthday, my moms birthday, and his own, same with christmas and holiday stuff no more needed to say, anyways, that means my mom does almost everything, my brother moved in november, im in a wheelchair, and my dad does a lot but has problems with focusing, i just wanted to say my back story, because if this comes out bad then fair, i am at my all time low, thats for real why i listen to the song named all time low, and i made that joke because jokes are the only thing that can make me laugh rn, another thing is that if this im about to say comes out bad im sorry, atleast ive told my back story, as i said in the last text i would want to know Noa's back story, then i would not have a problem with anything about if i make a joke about, his parents that are sadly not alive which hurts me to say, i would deserve it, i could go on about saying shit about you vet, but im not that guy, i also need to say a very very important thing, im 2 different people, i have a for real have a split life, i cant control it, im like the movie glass in a way, im sorry, this sounds dumb it does, and im sorry if i dont sound serious but i can be more serious in real life by talking, (not a threat btw), just a fact, i wont blame it on ADHD but its a thing that makes these other stuff worse, anyways i wont go on for longer, if i dont get threw i respect it more than anything, but just remember that i will keep on watching because i still respect you gys, - Tim

**Comment by Vetrnn** [comment]
Alright. Here is what is going to happen. We (Me, Noa, Alexa, Adam) will all write our points of view of this situation so you cant come after me saying im lying. So you will have 4 opinions from 4 diff people. These 4 people are the main unit of TCG

**Comment by Dadofall** [comment]
this is Noa , I will have to respectfully decline your ban appeal. we as a group have decided to keep u banned from here and ban u from twitch, as I would like to point out TCG is not just me it is a community of people , we as a community strive to help each other grow and find friendship among the weirdos and the crazys..... {me} and we can not have that tainted ... will not there is a point in time where i need to as some people say it have a backbone in certain situations and this is that time I am sorry that it had to come to this point ,i wish u happiness and all the well being on your future endeavors and luck on whatever you do. now on to the reasons why

1.parents
2.toxic
3.many many chances
4.being toxic outside of TCG



For reason #1 i know u may not remember about the parent jokes but I do and vett does as well it was on 1 of the first encounters on oblique

For reason #2 and #4 you have been toxic to some members of TCG ,it doesn't matter who just there has been toxicity between you and the community we built and for #4 the toxicity on oblique and other platform reflect poorly on TCG we are an all Inclusive group but even we have our limits when it hurts people around me and the TCG community i cannot stand for that this is where I put my foot down  


#3 We have given you many o many of chances on this , I know I have personally given you many of chances all you had to do was to put a little bit of effort in on making amends , righting the wrongs , showing me and the community that Tim is not just toxic, i have pleaded on your behalf to the community of people to give you another chance many of times but then you go and just do something else that just does not warrant another chance

My other mods and other people will be commenting and touching on this so please stand by for more


Take this as you will I Believe in you and hope the world for you

                                                                                                                                                                             Sincerely
                                                                                                                                                                               Noa

**Comment by Vetrnn** [comment]
I personally do not see a reason to keep you around anymore. You have proven to me to be full of lies. You say that you have never made fun of Noa's parents, yet we both know that is not the truth. We have had endless convos about your behavior, but for some reason you do not remember them? With Kata, with Noa, with me, etc. You have insulted both me and Noa, stuff that you shouldn't say to a person, and quite frankly, I do not care if you think its funny, you have a brain, and you should realize that shit like that you do not say. Period. I am not gonna start to explain what exactly you said, because this is public, and I will not make the fatal mistake off sharing it. While your apology may have some weight, it is too late for that now. We gave you endless chances and a handful more. If you somehow do not believe that I am telling the truth, then it just proves that you have not yet matured at all. Your not that guy pal. 

Now for my ultima arbitrium (Final decision in latin). I personally do not see a point in keeping u in this community. You have proven yourself to be more of a menace then a helping hand. I know there are communities out there that have the same sense of humor as you, and I urge you to find those communities. But as the manager of TCG, I do not think it is smart to unban you. Which leads me to my next point. Along with a ban from the discord server, I think this prompt a twitch ban as well. As I said previously, I do not think it is a smart move to have you part of TCG, not only for the reasons I have already gave, but for the better of the community. And as you said it in your own words: 

![](https://cdn.discordapp.com/attachments/757585766804226088/768388146248548352/Screen_Shot_2020-10-21_at_7.19.58_pm.png)

If I am a bitch to you, then at least we are on the same page, which that screenshot alone shows me that you do not wanna be part of this community. And I doubt you have changed your opinion, as I haven't changed mine, thus making my behavior the same as 9 months ago.

**Comment by Vetrnn** [comment]
Adam's opinion:

![image](https://user-images.githubusercontent.com/78167145/129462061-6ee907b9-188e-4596-9b2e-23e958e6237a.png)

**Comment by Alexabawesome** [comment]
Hello, this is Alexa, a mod for the Collective community. Based on what little interaction I have had with you and how you had acted, I don't think this community is the place for you. I am disappointed with your appeal; how it was worded as well as the fact that you chose to trauma dump. An unban appeal is not the place or the time to talk about your past personal experiences especially as this is public. I am sorry to see you have gone through so much in such a short time. However, also now knowing your age, I don't think you attending the streams and being part of the community is for the best. TCG is not a family friendly stream, not entirely 18+ either, but it is a more mature streaming atmosphere, which isn't the place for someone of your age and lack of maturity. 

I wish you the best,
Alexa

**Comment by ReflectedEight5** [comment]
i wont keep going, but when i did the parents joke i didnt know his parents where not alive, well ill be watching the streams anyways because i like watching him, idc what happens i will be watching the only thing i dont want is for Noa to block me on discord, because i will actually break, im not gonna try anymore, but i actually will die

**Comment by ReflectedEight5** [comment]
i really dont want to go on, but i swear i didnt know that Noa's parents where not alive until after i got banned from the town we where in, i swear, i did a joke then fair, but i did not know, nothing i will do about it, but Noa if you do see this plss dont block me just plss, i might not message you a lot, but i will keep an eye on you online thing so i can see when your streaming, nothing else i can do, nothing else i will do, goodbye 4 ever - Tim

**Comment by ReflectedEight5** [comment]
this is even worse day, to make this happen, i wont do anything about it this appeal, my brother got hit by a car today at 45 km per hour swedish km, he has just got a A-C broken Spine and got a lot of not life threat'ning idk how to say it in swedish conditions, just info from me today, im sorry you dont need to know this, you hate me anyways, gb 4 ever than, just plss dont block me Noa.
